-- DROP DATABASE
DROP DATABASE IF EXISTS techie_domain_db;

-- CREATE DATABASE
CREATE DATABASE techie_domain_db;

-- -- USE
-- USE 

-- -- DROP TABLE
-- DROP TABLE IF EXISTS
-- DROP TABLE IF EXISTS
-- DROP TABLE IF EXISTS
 
